class DataError(Exception):
    pass


class IdError(Exception):
    pass
